server:
  port: 8763
spring:
  application:
    name: eurekaclient
  rabbitmq:
    host: eurekaclient
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    publisherConfirms: true
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
